github:
  token:
Yi:
  owner: 01-ai
  repo: Yi
Qwen:
  owner: QwenLM
  repo: Qwen
Baichuan2:
  owner: baichuan-inc
  repo: Baichuan2
Baichuan-7B:
  owner: baichuan-inc
  repo: Baichuan-7B
Baichuan-13B:
  owner: baichuan-inc
  repo: Baichuan-13B
InternLM:
  owner: InternLM
  repo: InternLM
smaug:
  owner: harvard-acc
  repo: smaug
llama:
  owner: facebookresearch
  repo: llama
gemma:
  owner: google-deepmind
  repo: gemma
mistral:
  owner: mistralai
  repo: mistral-src
github_repo: [Yi, Qwen, Baichuan2, Baichuan-7B, Baichuan-13B, InternLM, llama, gemma, mistral]
hugging_face: [Yi, Qwen, Baichuan, InternLM, llama, gemma, mistral]
